// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('BaseApp.controllers').controller('CatalogCtrl', function($scope) {
  return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
});
