// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('BaseApp.controllers').controller('NavigatorCtrl', function($scope, $state) {
  $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  return $state.go('app.dashboard');
});
