// Generated by CoffeeScript 1.6.3
'use strict';
describe('Service: DBFactory', function() {
  var DBFactory;
  beforeEach(module('BaseApp'));
  DBFactory = {};
  beforeEach(inject(function(_DBFactory_) {
    return DBFactory = _DBFactory_;
  }));
  return it('should do something', function() {
    return expect(!!DBFactory).toBe(true);
  });
});
