// Generated by CoffeeScript 1.6.3
'use strict';
describe('Controller: NavigatorCtrl', function() {
  var NavigatorCtrl, scope;
  beforeEach(module('BaseApp'));
  NavigatorCtrl = {};
  scope = {};
  beforeEach(inject(function($controller, $rootScope) {
    scope = $rootScope.$new();
    return NavigatorCtrl = $controller('NavigatorCtrl', {
      $scope: scope
    });
  }));
  return it('should attach a list of awesomeThings to the scope', function() {
    return expect(scope.awesomeThings.length).toBe(3);
  });
});
