// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('BaseApp.services').service('DBFactory', function() {
  persistence.store.websql.config(persistence, 'incredibleDB', 'The incredible glasses local DB', 50 * 1024 * 1024);
  persistence.schemaSync();
  return this.exceptionHandler = function(callback) {
    return function(result, error) {
      if (error != null) {
        throw "SQLError code " + error.code + ": " + error.message;
      } else {
        return callback.apply(this, arguments);
      }
    };
  };
});
