// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('BaseApp', ['ngTouch', 'uiRouter', 'BaseApp.controllers']).config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise("/app/dashboard");
  return $stateProvider.state('app', {
    url: "/app",
    templateUrl: 'views/wrapper.html',
    controller: 'NavigatorCtrl'
  }).state('app.dashboard', {
    url: "/dashboard",
    templateUrl: 'views/dashboard.html',
    controller: 'DashboardCtrl'
  }).state('app.catalog', {
    url: "/catalog",
    templateUrl: 'views/catalog.html',
    controller: 'CatalogCtrl'
  });
});

angular.module("uiRouter", ["ui.router"]).run([
  "$rootScope", "$state", "$stateParams", function($rootScope, $state, $stateParams) {
    $rootScope.$state = $state;
    return $rootScope.$stateParams = $stateParams;
  }
]);

angular.module('BaseApp.controllers', ['BaseApp.services']);

angular.module('BaseApp.services', []);
